server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 20

spring:
  messages:
    basename: i18n/messages
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB
  devtools:
    restart:
      enabled: true

mybatis:
  typeAliasesPackage: com.ruoyi.student.domain
  mapperLocations: classpath*:mapper/**/*.xml
  configLocation: classpath:mybatis/mybatis-config.xml

logging:
  level:
    com.ruoyi: debug
    org.springframework: warn
